# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\GitHub\ASI-M1CB-PenToolBox-Interface\app\interface\ui\QemuInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QemuInterface(object):
    def setupUi(self, QemuInterface):
        QemuInterface.setObjectName("QemuInterface")
        QemuInterface.resize(1444, 914)
        QemuInterface.setMinimumSize(QtCore.QSize(1444, 914))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(QemuInterface)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(20, 40, 20, 20)
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.IconWidget_3 = IconWidget(QemuInterface)
        self.IconWidget_3.setMinimumSize(QtCore.QSize(50, 50))
        self.IconWidget_3.setMaximumSize(QtCore.QSize(50, 50))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/kali.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.IconWidget_3.setIcon(icon)
        self.IconWidget_3.setObjectName("IconWidget_3")
        self.horizontalLayout.addWidget(self.IconWidget_3)
        self.StrongBodyLabel = StrongBodyLabel(QemuInterface)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.StrongBodyLabel.setFont(font)
        self.StrongBodyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.horizontalLayout.addWidget(self.StrongBodyLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.QVNC = CardWidget(QemuInterface)
        self.QVNC.setMinimumSize(QtCore.QSize(1280, 800))
        self.QVNC.setMaximumSize(QtCore.QSize(1280, 800))
        self.QVNC.setObjectName("QVNC")
        self.verticalLayout.addWidget(self.QVNC, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(QemuInterface)
        QtCore.QMetaObject.connectSlotsByName(QemuInterface)

    def retranslateUi(self, QemuInterface):
        _translate = QtCore.QCoreApplication.translate
        QemuInterface.setWindowTitle(_translate("QemuInterface", "Form"))
        self.StrongBodyLabel.setText(_translate("QemuInterface", "Kali - Control Center"))
from qfluentwidgets import CardWidget, IconWidget, StrongBodyLabel
import app.resource.resource_rc